"""stock items deliveries counts sales expenses

Revision ID: 1e9b77c2922b
Revises: b39a5f2b7075
Create Date: 2026-07-06 10:23:05.505851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e9b77c2922b'
down_revision: Union[str, None] = 'b39a5f2b7075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_items',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('branch_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.String(length=12), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('branch_id', sa.String(length=12), nullable=False),
    sa.Column('item_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.String(length=12), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_counts',
    sa.Column('branch_id', sa.String(length=12), nullable=False),
    sa.Column('item_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_remaining', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.String(length=12), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_deliveries',
    sa.Column('branch_id', sa.String(length=12), nullable=False),
    sa.Column('item_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_delivered', sa.Float(), nullable=False),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=12), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_deliveries')
    op.drop_table('stock_counts')
    op.drop_table('sales')
    op.drop_table('expenses')
    op.drop_table('stock_items')
    # ### end Alembic commands ###
